messages:
  text:
    invalid_comand: "К сожалению, я не знаю такой команды =("
    bot_is_started: "Бот уже запущен, введи другую команду"
    hello: "Здравствуй! Ты запустил помощника по Википедии. Для начала, давай выберем язык, на которм ты будешь видеть информацию. Вот список доступных языков:\nБеларуская\nEnglish\nNederlands\nРусский\n\nНапиши выбранный язык в новом сообщении так же, как в примере выше 👆\nЕсли ты пропустишь это действие, по умолчанию будет установлен Русский язык.\nДля просмотра доступных команд используй — /help"
    new_language: "Выбери новый язык из доступных:\nБеларуская\nEnglish\nNederlands\nРусский\n\nНапиши его в новом сообщении так же, как в примере выше 👆"
    new_query: "Введите вопрос"
    rus_install: "Русский язык успешно установлен"
    bel_install: "Беларуская язык успешно установлен"
    en_install: "English язык успешно установлен"
    nl_install: "Nederlands язык успешно установлен"
    invalid_input: "Некорректный ввод"
    see_comand: "\nДля просмотра доступных команд используйте: /help"
    comand: "Доступные вам команды:\n/language — меняет язык статей Википедии\n/random  — выводит рандомную статью\n/query      — выводит статью по вашему вопросу\n/help        — помощь"
  
  comands:
    start: "start"
    reset_language: "language"
    random: "random"
    query: "query"
    help: "help"